version: "3"
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  app:
    build: .
    ports:
      - "8080:8000"
    # volumes:
    #   - ./312Not-Local:/root # Ensure this maps the current directory to /root in the container
  mongo:
    image: mongo
    ports:
      - "27017:27017"
