version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - my_volume:/app/public/images/

volumes:
  my_volume:
